# Generated by Django 5.2.7 on 2025-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='type',
            field=models.CharField(choices=[('ZTT', 'Zone de Transit et de Tri'), ('RES', 'Résidence'), ('ENT', 'Entreprise'), ('COM', 'Commerce'), ('AUT', 'Autre')], default='RES', max_length=3),
        ),
    ]
